### PR TITLE
Fixes for AMD compilers

### PR DESCRIPTION
**Pull request by thilinarmtb**

### CODE REVIEW

**Comment by stgeke** [comment]
What was the actual issue?

**Comment by yslan** [comment]
This seems to fix the "Floating point exception" error. Tested with kershaw66 case, running on 4 Frontier nodes.

**Comment by stgeke** [comment]
Let me ask differently: Can you please explain why the FP-exception happened and how you fixed it.

**Comment by thilinarmtb** [comment]
@stgeke : It was actually a bug on my part that comes up when two level partitioning is on. I guess for GCC, somehow the
floating point exception was not raised.

**Pull request merged**
