### PR TITLE
Add an option to turn-off disconnected components calculation

### PR DESCRIPTION
**Pull request by thilinarmtb**
Stop finding the number of disconnected components in the generated partitions.
This takes a very long time when the number of disconnected components are in the
order of 100.

### TODO

- [x] Test the branch on a bigger mesh at scale before merging.

### CODE REVIEW

**Comment by stgeke** [comment]
Is the warning that there are many disconnected components?

**Comment by yslan** [comment]
For our chimera case (E=1.69Bn), it prints something like this and take a very long time
```
Warning: Lanczos reached a residual of 0.000014 (target: 0.000010) after 50 x 50 iterations in Level=15!
Warning: Partition created 1/1999 (min/max) disconnected components in Level=15!
parrsb_part_mesh_v0: restore original input
parRSB finished in 3261.12 seconds.
```

**Comment by thilinarmtb** [comment]
> Is the warning that there are many disconnected components?

Yes, it takes a long time if there are a large number of disconnected components.

**Comment by stgeke** [comment]
I wanted to say that having no warning at all is also not a good option.

**Comment by thilinarmtb** [comment]
What would be a good compromise? Shall we enable finding disconnected components
by default and then have an option to disable it if required?

**Comment by stgeke** [comment]
Yeah or we only turn it on for the first N levels.

**Comment by thilinarmtb** [comment]
@stgeke : I added an option to turn-off finding disconnected components if necessary. User can do:
```sh
export PARRSB_FIND_NUM_COMPONENTS=0
```

in order to turn it off. Or this can be set in in the `parrsb_options` struct when parRSB is called with
the C API.

**Comment by stgeke** [comment]
I find the name a bit confusing. How about renaming it to `PARRSB_FIND_DISCONNECTED_COMPONENTS `?

**Pull request merged**
